baseURL = "https://m.shishutours.fun"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Affordable holidays - tour planner in Nepal | ShiShu Tours"
# Main Menu
[[menu.main]]
#name = "Home"
#url = "#home"
#weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 1
#[[menu.main]]
#name = "Service"
#url = "#service"
#weight = 3
[[menu.main]]
name = "Inbound"
url = "#blog"
weight = 3
[[menu.main]]
name = "Outbound"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 5

# Sitemap Menu
[[menu.sitemap]]
name = "About us "
url = "about"
weight = 1
[[menu.sitemap]]
name = "Browse All Trips"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Golden Visa"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © ShiShu Tours & Travel Pvt. Ltd. 2021"
footerLogo = "images/logo.jpg"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "https://res.cloudinary.com/shishutours/image/upload/v1608177256/cropped-imageedit_1_4410750631_p6ogff.png"

[params.address]
address = "Lamzipat, Kathmandu, 44600, Nepal"
email = "info@shishutours.fun"
openingHours = "Open from 10am to 6pm (close on Saturday)"
phone = "+(977) 14428559"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/ShiShuTour"
weight = 1
#[[params.social]]
#icon = "fa-linkedin-square"
#url = "https://www.linkedin.com/"
#weight = 2
#[[params.social]]
#icon = "fa-pinterest-square"
#url = "https://www.pinterest.com/"
#weight = 3
#[[params.social]]
#icon = "fa-twitter-square"
#url = "https://twitter.com/"
#weight = 4

# Cloudinary
cloudinary_url = "https://res.cloudinary.com/shishutours/image/upload"
